### ISSUE TITLE
Unable to use aioflask with Flask 2.2.0+

### ISSUE THREAD

**Issue by samsara-team** [miguelgrinberg/aioflask#10]
When attempting to use the latest aioflask with Flask 2.2.0+ the following import error comes up:

Traceback (most recent call last):
  File "...", line 1, in <module>
    from aioflask import Flask, request
  File "...\aioflask\__init__.py", line 2, in <module>
    from .app import Flask
  File "...\aioflask\app.py", line 14, in <module>
    from .ctx import AppContext, RequestContext
  File "...\aioflask\ctx.py", line 4, in <module>
    from flask.ctx import AppContext as OriginalAppContext, \
ImportError: cannot import name '_app_ctx_stack' from 'flask.ctx' (...site-packages\flask\ctx.py)

There seems to be a breaking change in 2.2.0, which should be considered in aioflask.

**Comment by SheikhHassaanBinNadeem** [comment]
Still getting same issue while connecting mysqldb with Flask to post data. Had to downgrade to older version to make it work.

> "from flask import _app_ctx_stack, current_app
> ImportError: cannot import name '_app_ctx_stack' from 'flask'"
