### ISSUE TITLE
TypeError: render_template() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by cobaltgit** [miguelgrinberg/aioflask#8]
When returning a render template with a context, the context argument raises an exception.
```python
Traceback (most recent call last):
  File "/home/cobalt/.local/share/virtualenvs/Minecraft_Website-ZyKV6NXV/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cobalt/.local/share/virtualenvs/Minecraft_Website-ZyKV6NXV/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cobalt/.local/share/virtualenvs/Minecraft_Website-ZyKV6NXV/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cobalt/.local/share/virtualenvs/Minecraft_Website-ZyKV6NXV/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/cobalt/.local/share/virtualenvs/Minecraft_Website-ZyKV6NXV/lib/python3.8/site-packages/aioflask/app.py", line 47, in wrapped
    return await_(_coro())
  File "/home/cobalt/.local/share/virtualenvs/Minecraft_Website-ZyKV6NXV/lib/python3.8/site-packages/greenletio/core.py", line 130, in await_
    return parent.switch(coro_or_fn)
  File "/home/cobalt/.local/share/virtualenvs/Minecraft_Website-ZyKV6NXV/lib/python3.8/site-packages/greenletio/core.py", line 88, in wrapper
    result = await coro
  File "/home/cobalt/.local/share/virtualenvs/Minecraft_Website-ZyKV6NXV/lib/python3.8/site-packages/aioflask/app.py", line 41, in _coro
    ret = await func(*args, **kwargs)
  File "/home/cobalt/Documents/Code/Python/Minecraft Website/app/routes.py", line 17, in root
    return await render_template("index.html", context.home)
```
Here's some code if it helps:
```py
from app.contexts import Contexts
...
context = Contexts()

@app.route("/")
async def root():
    context.home.update({
        "ip_address": SERVER_IP,
        "port": SERVER_PORT,
        "api_endpoint": API_ENDPOINT
    })
    return await render_template("index.html", context.home)
```
```py
class Contexts:
    def __init__(self):
        self.CONTEXT_BASE = {"title": "CobaltMC"}
        self.home = self.CONTEXT_BASE
        self.tutorial = self.CONTEXT_BASE
```

**Comment by cobaltgit** [comment]
Silly me, I forgot to unpack the dict
